"""empty message

Revision ID: 1f8c938e31b1
Revises: c1e4820bc86
Create Date: 2015-10-07 16:45:02.327962

"""

# revision identifiers, used by Alembic.
revision = '1f8c938e31b1'
down_revision = 'c1e4820bc86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', 'users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    ### end Alembic commands ###
